### ISSUE TITLE
-DUSE_WAYLAND_WSI=ON results in link failure (missing vkCreateWaylandSurfaceKHR)

### ISSUE THREAD

**Issue by eliasnaur** [SaschaWillems/Vulkan#435]
On Fedora 27 and running Wayland, building the examples with -DUSE_WAYLAND_WSI=ON fails:

````
$ cmake -DUSE_WAYLAND_WSI=ON
...
$ make
[  5%] Built target base
[  6%] Linking CXX executable ../bin/viewportarray
../base/libbase.a(vulkanexamplebase.cpp.o): In function `VulkanSwapChain::initSurface(wl_display*, wl_surface*)':
vulkanexamplebase.cpp:(.text._ZN15VulkanSwapChain11initSurfaceEP10wl_displayP10wl_surface[_ZN15VulkanSwapChain11initSurfaceEP10wl_displayP10wl_surface]+0xad): undefined reference to `vkCreateWaylandSurfaceKHR'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/viewportarray.dir/build.make:101: bin/viewportarray] Error 1
make[1]: *** [CMakeFiles/Makefile2:261: examples/CMakeFiles/viewportarray.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
````

However, vulkaninfo seems to indicate that VK_KHR_wayland_surface is supported:

````
$ vulkaninfo | grep VK_KHR_wayland_surface
	VK_KHR_wayland_surface              : extension revision  6
````

Did I miss anything? Building with -DUSE_WAYLAND_WSI=OFF works, but fails at runtime:

````
$ cmake -DUSE_WAYLAND_WSI=OFF
...
$ make
...
$ ./bin/triangle 
Segmentation fault (core dumped)
$ gdb ./bin/triangle 
GNU gdb (GDB) Fedora 8.0.1-36.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/triangle...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/elias/snot/Vulkan/bin/triangle 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-24.fc27.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000015000000150 in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install assimp-3.3.1-12.fc27.x86_64 bzip2-libs-1.0.6-24.fc27.x86_64 elfutils-libelf-0.170-1.fc27.x86_64 irrXML-1.8.4-1.fc27.3.x86_64 libX11-1.6.5-4.fc27.x86_64 libX11-xcb-1.6.5-4.fc27.x86_64 libXau-1.0.8-9.fc27.x86_64 libXext-1.3.3-7.fc27.x86_64 libXxf86vm-1.1.4-6.fc27.x86_64 libaesgm-20090429-15.fc27.x86_64 libdrm-2.4.89-1.fc27.x86_64 libedit-3.1-20.20170329cvs.fc27.x86_64 libffi-3.1-14.fc27.x86_64 libgcc-7.3.1-2.fc27.x86_64 libglvnd-1.0.0-1.fc27.x86_64 libglvnd-glx-1.0.0-1.fc27.x86_64 libjpeg-turbo-1.5.3-1.fc27.x86_64 libpng-1.6.31-1.fc27.x86_64 libstdc++-7.3.1-2.fc27.x86_64 libwayland-client-1.14.0-2.fc27.x86_64 libwayland-server-1.14.0-2.fc27.x86_64 libxcb-1.12-5.fc27.x86_64 libxshmfence-1.2-6.fc27.x86_64 llvm-libs-5.0.1-3.fc27.x86_64 mesa-vulkan-drivers-17.2.4-3.fc27.x86_64 minizip-1.2.11-4.fc27.x86_64 ncurses-libs-6.0-13.20170722.fc27.x86_64 poly2tri-0.0-14.20130501hg26242d0aa7b8.fc27.x86_64 zlib-1.2.11-4.fc27.x86_64
(gdb) bt
#0  0x0000015000000150 in ?? ()
#1  0x00007ffff79971ee in terminator_CreateXcbSurfaceKHR () from /home/elias/snot/Vulkan/libs/vulkan/libvulkan.so.1
#2  0x0000000000461876 in VulkanSwapChain::initSurface(xcb_connection_t*, unsigned int) ()
#3  0x00000000004600d9 in VulkanExampleBase::initSwapchain() ()
#4  0x0000000000459e3b in VulkanExampleBase::prepare() ()
#5  0x0000000000451662 in VulkanExample::prepare() ()
#6  0x000000000044a98e in main ()
````

**Comment by SaschaWillems** [comment]
I don't have any wayland platform to test, but it's possible that you have to manually load the function pointers for e.g. ```vkCreateWaylandSurfaceKHR``` using ```vkGetInstanceProcAddr```.

**Comment by SaschaWillems** [comment]
Closing due to inactivity.
